import LocalizedStrings from 'react-localization';

export const copy = new LocalizedStrings({
  en: {
    leftNavButton: 'Notifications',
    centerNavButton: 'Do Something',
    rightNavButton: 'Settings',
    activityFavoritesText: 'Favorites',
    activityFavoritesEmptyState: 'No favorites to see here, yet!',
    foodActivityTile: 'Get Food',
    outsideActivityTile: 'Explore Nature',
    workoutActivityTile: 'Go Workout',
    shopActivityTile: 'Go Shop',
    coffeeActivityTile: 'Get Coffee',
    relaxActivityTile: 'Chill Out',
    nightlifeActivityTile: 'Nightlife',
    entertainmentActivityTile: 'Entertainment',
    artAndCultureActivityTile: 'Art & Culture',
    favoritesActivityTile: 'Favorites',
    defaultActivityTile: 'Search Results',
    activitySelectorTitle: 'Do Something',
    activitySelectorSubtitle: 'I want to invite my friends to...',
    activitySelectorSearchPlaceholder: 'Search for Restaurants, Parks, ...',
    confirmPlanTitle: 'Finalize',
    confirmPlanSubtitle:
      'Almost done! Please confirm all details are correct, and that you’ve invited all you want. You can always come back and edit this event at a later time.',
    planNameRequired: 'What do you want to do? *',
    dateRequired: 'What day? *',
    timeRequired: 'What time? *',
    createPlanDescription: 'Any other info:',
    createPlanAddress: 'Address:',
    createPlanNonUserMessage: 'Friends who don’t have Groupify yet will receive the following message:',
    createPlanEditMessageTitle: 'Edit message',
    confirmPlanButtonText: 'Create plan!',
    createAccountPageTitle: 'Create account',
    firstNameFieldTitle: 'First Name',
    lastNameFieldTitle: 'Last Name',
    phoneNumberFieldTitle: 'Phone Number',
    passwordFieldTitle: 'Password',
    confirmPasswordFieldTitle: 'Confirm Password',
    nextButtonTitle: 'next',
    findAddressOnMap: 'Find address using the map',
    askForVerificationCode: 'Please enter the verification code you received.',
    forgotPasswordTitle: 'Forgot Password',
    phoneNumberPrompt: 'Please enter your phone number',
    createNewPassword: 'Create a new password',
  },
});
