import LocalizedStrings from 'react-localization';

export const copy = new LocalizedStrings({
  en: {
    leftNavButton: 'Notifications',
    centerNavButton: 'Do Something',
    rightNavButton: 'Profile',
    acticitySelectorOrText: 'or',
    altrenateActivityText: 'Do something else',
    activitySelectorHelpButton: '?',
    activityFavoritesText: 'Favorites',
    activityFavoritesEmptyState: 'No favorites to see here, yet!',
    foodActivityTile: 'Get Food',
    outsideActivityTile: 'Explore Nature',
    workoutActivityTile: 'Go Workout',
    shopActivityTile: 'Go Shop',
    coffeeActivityTile: 'Get Coffee',
    relaxActivityTile: 'Chill Out',
    nightlifeActivityTile: 'Nightlife',
    entertainmentActivityTile: 'Entertainment',
    artAndCultureActivityTile: 'Art & Culture',
    favoritesActivityTile: 'Favorites',
    defaultActivityTile: 'Search Results',
    activitySelectorTitle: 'Do Something',
    activitySelectorSubtitle: 'I want to invite my friends to...',
    activitySelectorSearchPlaceholder: 'Search for Restaurants, Parks, ...',
    confirmPlanTitle: 'Finalize',
    confirmPlanSubtitle:
      'Almost done! Please confirm all details are correct, and that you’ve invited all you want. You can always come back and edit this event at a later time.',
    planNameRequired: 'What do you want to do? *',
    dateRequired: 'What day? *',
    timeRequired: 'What time? *',
    createPlanDescription: 'Any other info:',
    createPlanAddress: 'Address:',
    createPlanNonUserMessage: 'Friends who don’t have Groupify yet will receive the following message:',
    createPlanEditMessageTitle: 'Edit message',
    confirmPlanButtonText: 'Create plan!',
    createAccountPageTitle: 'Create account',
    firstNameFieldTitle: 'First Name',
    lastNameFieldTitle: 'Last Name',
    phoneNumberFieldTitle: 'Phone Number',
    passwordFieldTitle: 'Password',
    confirmPasswordFieldTitle: 'Confirm Password',
    nextButtonTitle: 'Next',
    findAddressOnMap: 'Find address using the map',
    askForVerificationCode: 'Please enter the verification code you received.',
    forgotPasswordTitle: 'Forgot Password',
    phoneNumberPrompt: 'Please enter your phone number',
    createNewPassword: 'Create a new password',
    upcomingPlansTitle: 'COMING UP NEXT',
    helloNameMessage: 'Hello, ',
    yourPlansTitle: 'YOUR PLANS',
    createdPlansTitle: 'CREATED PLANS',
    createdPlansDescription:
      'Welcome to your plan dashboard. This is where you will see a round-up of plans you’ve created, and things you&apos;re invited to.',
    createFirstPlanText: 'Create your first plan with the button below',
    noPendingPlans: 'No pending plans at the moment',
    pendingTitle: 'PENDING',
    acceptedTitle: 'ACCEPTED',
    youCanCreateAPlanTitle: 'You can create one!',
    noPlansAccepted: 'Looks like you haven’t accepted any plans',
    askForContactsPrompt: 'Add friends from your contact list to make plans!',
    editContactsLaterPrompt: '*You can always edit your contact list later. ',
    selectContactsTitle: 'Select Contacts',
    skipSelectContactsButton: 'Skip',
    importContactsButton: 'Add Friends',
    confirmNoContactsImport: 'Are you sure you don’t want to import contacts?',
    noContactsImported:
      'You must have contacts to make plans with, or to find plans being created. You can always edit your contact list later.',
    yourInvitees: 'Your Invitees',
    thisWeek: 'This Week',
    pendingInvites: 'Pending Invites',
    pastPlans: 'Past Plans',
    whenInvitedToPlanTitle: 'When you get invited to a plan, it will show up here',
    forgotPasswordQuestion: 'Forgot password?',
    dontHaveAnAccountQuestion: 'Don’t have an account?',
    loginButtonTitle: 'Log In',
    createAPlanTitle: 'Create a Plan',
    inviteFriendsButton: 'Invite Friends',
    planDetailsTitle: 'Plan Details',
    whosGoing: 'Who’s Going?',
    notificationsTitle: 'All Plans',
    invitedNotificationsTitle: 'INVITED',
    createdNotificationsTitle: 'CREATED',
    confirmInviteDeclineText: 'Are you sure you’d like to decline this invitation?',
    confirmDeclineText: 'Yes, Decline',
    cancelDeclineText: 'No',
    inviteDeclined: 'Invite has been declined',
    confirm: 'Okay',
    celebrationText: 'Woot!',
    inviteAcceptedConfirmation: 'You’ve accepted an invite!',
    whoToInvite: 'Who do you want to invite to ',
    lookForFriends: 'Search for friends to invite',
    previewPlan: 'Preview plan',
    addFriendsButtonTitle: 'Add Friends',
    submitBugReportButtonTitle: 'Submit Bug Report',
    signUpButtonTitle: 'Sign Up',
    distanceMeasure: 'mi',
  },
});
