export const data = [
  {
    division: 'Admin',
    name: 'Griffin Clark',
    title: 'Chief Executive Officer',
    country: 'US',
    linkedIn: 'https://www.linkedin.com/in/griffin-clark-ml/',
  },
  {
    division: 'Admin',
    name: 'Isaac Mclaurin',
    title: 'Head of Operations',
    country: 'US',
    linkedIn: 'https://www.linkedin.com/in/isaac-mclaurin-b23a09161/',
  },
  {
    division: 'Admin',
    name: 'Trent Suzuki',
    title: 'Head Of Talent Acquisition and Development',
    country: 'US',
    linkedIn: 'https://www.linkedin.com/in/trent-suzuki-3b44a21b/',
  },
  {
    division: 'Admin',
    name: 'Saddaf Mehar',
    title: 'Executive Assistant',
    country: 'US',
    linkedIn: 'https://www.linkedin.com/in/saddaf-mehar/',
  },
  {
    division: 'Admin',
    name: 'Keith McClellan',
    title: 'Corporate Attourney',
    country: 'US',
    linkedIn: 'https://www.linkedin.com/in/keith-l-mcclellan-esq-mba-0b9165113/',
  },
  {
    division: 'Development',
    name: 'Joni Beyster',
    title: 'Design Lead',
    country: 'US',
    linkedIn: 'https://www.linkedin.com/in/🤓-joni-beyster-73991577/',
  },
  {
    division: 'Development',
    name: 'Anuj Kapoor',
    title: 'Technical Product Manager',
    country: 'DE',
    linkedIn: 'https://www.linkedin.com/in/anuj-kapoor-642387158/',
  },
  {
    division: 'Development',
    name: 'Hassan Khan',
    title: 'Quality Assurance Lead',
    country: 'PK',
    linkedIn: 'https://www.linkedin.com/in/muhammad-hassaan-khan-15a890194/',
  },
  {
    division: 'Development',
    name: 'Trang Vo',
    title: 'Frontend Development Guru',
    country: 'VN',
    linkedIn: 'https://www.linkedin.com/in/trangvo2306/',
  },
  {
    division: 'Development',
    name: 'Andrei Sebald',
    title: 'Backend Developer',
    country: 'US',
    linkedIn: 'https://www.linkedin.com/in/andreisebald/',
  },
  {
    division: 'Development',
    name: 'Casey Pearce',
    title: 'User Experience Copywriter',
    country: 'US',
    linkedIn: 'https://www.linkedin.com/in/casey-pearce-copy-by-casey/',
  },
  {
    division: 'Development',
    name: 'Ernest Nnamdi',
    title: 'Full Stack Developer',
    country: 'NG',
    linkedIn: 'https://www.linkedin.com/in/ernest-molokwu/',
  },
  {
    division: 'Development',
    name: 'Ruphine Kengne',
    title: 'Backend Developer',
    country: 'CM',
    linkedIn: 'http://linkedin.com/in/tcheukounang-grace-6a5169124',
  },
  {
    division: 'Development',
    name: 'Vanishree Dhanasekaran',
    title: 'Quality Assurance Engineer',
    country: 'US',
    linkedIn: 'https://www.linkedin.com/in/vanidhana/',
  },
  {
    division: 'Marketing',
    name: 'Julia Most',
    title: 'Growth Marketing Lead',
    country: 'US',
    linkedIn: 'https://www.linkedin.com/in/juliamost/',
  },
  {
    division: 'Marketing',
    name: 'Kushagra',
    title: 'Performance Marketing Lead',
    country: 'IN',
    linkedIn: 'https://www.linkedin.com/in/kushagra-748500a7/',
  },
  {
    division: 'Marketing',
    name: 'Christina Okhotin',
    title: 'Copywriter',
    country: 'US',
    linkedIn: 'https://www.linkedin.com/in/christina-okhotin/',
  },
  {
    division: 'Marketing',
    name: 'Holly Hanger',
    title: 'Growth Marketer',
    country: 'US',
    linkedIn: 'https://www.linkedin.com/in/holly-hanger-21abb917a/',
  },
  {
    division: 'Marketing',
    name: 'Mariajose Garcia',
    title: 'Graphics Designer',
    country: 'US',
    linkedIn: 'https://www.linkedin.com/in/mariajose-garcia-badillo-a7058133/',
  },
  {
    division: 'Marketing',
    name: 'Swar Jain',
    title: 'Influencer Marketing Specialist',
    country: 'US',
    linkedIn: 'https://www.linkedin.com/in/swarjain/',
  },
  {
    division: 'Advisors',
    name: 'Micheal McCafferty',
    country: 'US',
    linkedIn: 'https://www.linkedin.com/in/michaelmccafferty/',
  },
  {
    division: 'Advisors',
    name: 'Paul Smith',
    country: 'US',
    linkedIn: 'https://www.linkedin.com/in/paulsmith111/',
  },
  {
    division: 'Advisors',
    name: 'Seth Greenberg',
    country: 'US',
    linkedIn: 'https://www.linkedin.com/in/sethgreenberg/',
  },
  {
    division: 'Advisors',
    name: 'Steve Clark',
    country: 'US',
    linkedIn: 'https://www.linkedin.com/in/steve-clark-cto/',
  },
];
