// Auto-generated file created by react-native-storybook-loader
// Do not edit.
//
// https://github.com/elderfo/react-native-storybook-loader.git

function loadStories() {
  require('./stories/ActivityCard.stories');
  require('./stories/ActivityImage.stories');
  require('./stories/ActivityList.stories');
  require('./stories/ActivityMap.stories');
  require('./stories/ActivityModal.stories');
  require('./stories/Alert.stories');
  require('./stories/AlertModal.stories');
  require('./stories/AppText.stories');
  require('./stories/AppTextInput.stories');
  require('./stories/BottomButton.stories');
  require('./stories/Button.stories');
  require('./stories/CheckBox.stories');
  require('./stories/CircularImageDisplay.stories');
  require('./stories/ContactContainer.stories');
  require('./stories/ContactsModal.stories');
  require('./stories/ContactTile.stories');
  require('./stories/CreatedPlans.stories');
  require('./stories/CreatedPlanTile.stories');
  require('./stories/DataDisplay.stories');
  require('./stories/Details.stories');
  require('./stories/EventTile.stories');
  require('./stories/FormButton.stories');
  require('./stories/FormInput.stories');
  require('./stories/FriendBubble.stories');
  require('./stories/FriendContainer.stories');
  require('./stories/FriendList.stories');
  require('./stories/GroupifyForm.stories');
  require('./stories/HomeNavBar.stories');
  require('./stories/InviteePreviewTile.stories');
  require('./stories/MediumPlanTile.stories');
  require('./stories/MiniPlanTile.stories');
  require('./stories/MultiLineTextInput.stories');
  require('./stories/Navbar.stories');
  require('./stories/Navbar2.stories');
  require('./stories/NavButton.stories');
  require('./stories/NoResults.stories');
  require('./stories/PlaceCard.stories');
  require('./stories/PlanDetailsTile.stories');
  require('./stories/PlanImageTile.stories');
  require('./stories/PlanTextMessage.stories');
  require('./stories/Screen.stories');
  require('./stories/SearchBar.stories');
  require('./stories/SingleLineTextInput.stories');
  require('./stories/SquareImageDisplay.stories');
  require('./stories/Tile.stories');
  require('./stories/TwoButtonAlert.stories');
  require('./stories/ViewAll.stories');
  require('./stories/WhiteButton.stories');
}

const stories = [
  './stories/ActivityCard.stories',
  './stories/ActivityImage.stories',
  './stories/ActivityList.stories',
  './stories/ActivityMap.stories',
  './stories/ActivityModal.stories',
  './stories/Alert.stories',
  './stories/AlertModal.stories',
  './stories/AppText.stories',
  './stories/AppTextInput.stories',
  './stories/BottomButton.stories',
  './stories/Button.stories',
  './stories/CheckBox.stories',
  './stories/CircularImageDisplay.stories',
  './stories/ContactContainer.stories',
  './stories/ContactsModal.stories',
  './stories/ContactTile.stories',
  './stories/CreatedPlans.stories',
  './stories/CreatedPlanTile.stories',
  './stories/DataDisplay.stories',
  './stories/Details.stories',
  './stories/EventTile.stories',
  './stories/FormButton.stories',
  './stories/FormInput.stories',
  './stories/FriendBubble.stories',
  './stories/FriendContainer.stories',
  './stories/FriendList.stories',
  './stories/GroupifyForm.stories',
  './stories/HomeNavBar.stories',
  './stories/InviteePreviewTile.stories',
  './stories/MediumPlanTile.stories',
  './stories/MiniPlanTile.stories',
  './stories/MultiLineTextInput.stories',
  './stories/Navbar.stories',
  './stories/Navbar2.stories',
  './stories/NavButton.stories',
  './stories/NoResults.stories',
  './stories/PlaceCard.stories',
  './stories/PlanDetailsTile.stories',
  './stories/PlanImageTile.stories',
  './stories/PlanTextMessage.stories',
  './stories/Screen.stories',
  './stories/SearchBar.stories',
  './stories/SingleLineTextInput.stories',
  './stories/SquareImageDisplay.stories',
  './stories/Tile.stories',
  './stories/TwoButtonAlert.stories',
  './stories/ViewAll.stories',
  './stories/WhiteButton.stories',
];

module.exports = {
  loadStories,
  stories,
};
